apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["us-west-2a", "us-west-2b"]
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"]
  limits:
    resources:
      cpu: 1k
  provider:
    subnetSelector:
      karpenter.sh/discovery: team-2-eks
    securityGroupSelector:
      karpenter.sh/discovery: team-2-eks
  ttlSecondsAfterEmpty: 30
